default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: develop
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: tv_api_development

test:
  <<: *default
  database: tv_api_test

production:
  <<: *default
  database: tv_api
